#!/bin/bash
echo Preparing to copy files...

cp textarraymodel.js ../myCMS/models/
cp textarray.js ../myCMS/routes/api/
cp textarray-test1.html ../myCMS/public/
cp textarray-test2.html ../myCMS/public/